name: CI
on:
  push:
    tags: [v*.*.*]
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: "./.nvmrc"
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run format:check
      - name: Run eslint
        run: npm run lint
      - name: Build project
        run: npm run build
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run Black formatter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
